[versions]
androidGradlePlugin = "8.13.1"
kotlin = "2.2.21"
spotless = "8.0.0"
versions = "0.51.0"
errorprone = "4.3.0"
coveralls = "2.12.2"
jacocoAndroid = "0.2.1"
easylauncher = "6.4.1"
pythonUv = "0.3.4"
appVersioning = "1.5.0"
room = "2.8.3"
ksp = "2.3.2"

compileSdk = "36"
minSdk = "23"
targetSdk = "35"

composeBom = "2025.11.00"
lifecycleViewModel = "2.9.4"
navigationCompose = "2.9.6"
activityCompose = "1.11.0"

sshlib = "2.2.32"
playServicesBasement = "18.9.0"
conscrypt = "2.5.3"
conscryptOpenJdk = "2.5.2"
coroutines = "1.10.2"

recyclerview = "1.4.0"
appcompat = "1.7.1"
preference = "1.2.1"
material = "1.13.0"

testCore = "1.7.0"
testOrchestrator = "1.6.1"
testRunner = "1.7.0"
espresso = "3.7.0"
junit = "1.3.0"

junitClassic = "4.13.2"
mockito = "5.20.0"
mockitoKotlin = "6.1.0"
assertj = "3.27.6"
robolectric = "4.16"

errorproneCore = "2.44.0"

[libraries]
sshlib = { module = "org.connectbot:sshlib", version.ref = "sshlib" }
play-services-basement = { module = "com.google.android.gms:play-services-basement", version.ref = "playServicesBasement" }
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }

androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
material = { module = "com.google.android.material:material", version.ref = "material" }

androidx-test-core = { module = "androidx.test:core", version.ref = "testCore" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "testOrchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "testRunner" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }

junit = { module = "junit:junit", version.ref = "junitClassic" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
conscrypt-openjdk-uber = { module = "org.conscrypt:conscrypt-openjdk-uber", version.ref = "conscryptOpenJdk" }

errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorproneCore" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewModel" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone" }
coveralls = { id = "com.github.kt3k.coveralls", version.ref = "coveralls" }
jacoco-android = { id = "com.mxalbert.gradle.jacoco-android", version.ref = "jacocoAndroid" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
python-uv = { id = "com.pswidersk.python-uv-plugin", version.ref = "pythonUv" }
app-versioning = { id = "io.github.reactivecircus.app-versioning", version.ref = "appVersioning"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
