[versions]
androidGradlePlugin = "9.0.0"
kotlin = "2.3.0"
spotless = "8.2.1"
versions = "0.53.0"
errorprone = "5.0.0"
coveralls = "2.12.2"
jacocoAndroid = "0.2.1"
easylauncher = "6.4.1"
pythonUv = "0.3.14"
appVersioning = "1.5.0"
room = "2.8.4"
ksp = "2.3.5"
hilt = "2.59"
hiltNavigationCompose = "1.3.0"

compileSdk = "36"
minSdk = "24"
targetSdk = "35"

composeBom = "2026.01.00"
material3 = "1.5.0-alpha12"
lifecycleViewModel = "2.10.0"
navigationCompose = "2.9.6"
activityCompose = "1.12.2"

sshlib = "2.2.40"
termlib = "0.0.17"
playServicesBasement = "18.10.0"
conscrypt = "2.5.3"
conscryptOpenJdk = "2.5.2"
coroutines = "1.10.2"
timber = "5.0.1"

recyclerview = "1.4.0"
appcompat = "1.7.1"
preference = "1.2.1"
material = "1.13.0"

testCore = "1.7.0"
testOrchestrator = "1.6.1"
testRunner = "1.7.0"
espresso = "3.7.0"
junit = "1.3.0"

junitClassic = "4.13.2"
mockito = "5.21.0"
mockitoKotlin = "6.2.3"
assertj = "3.27.7"
robolectric = "4.16.1"

errorproneCore = "2.46.0"
media3CommonKtx = "1.9.1"
navigationTesting = "2.9.6"
ui = "1.10.1"
biometric = "1.4.0-alpha02"
core = "1.17.0"

[libraries]
sshlib = { module = "org.connectbot:sshlib", version.ref = "sshlib" }
termlib = { module = "org.connectbot:termlib", version.ref = "termlib" }
play-services-basement = { module = "com.google.android.gms:play-services-basement", version.ref = "playServicesBasement" }
conscrypt-android = { module = "org.conscrypt:conscrypt-android", version.ref = "conscrypt" }

androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
material = { module = "com.google.android.material:material", version.ref = "material" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

androidx-test-core = { module = "androidx.test:core", version.ref = "testCore" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "testOrchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "testRunner" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }

junit = { module = "junit:junit", version.ref = "junitClassic" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
conscrypt-openjdk-uber = { module = "org.conscrypt:conscrypt-openjdk-uber", version.ref = "conscryptOpenJdk" }

errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorproneCore" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleViewModel" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone" }
coveralls = { id = "com.github.kt3k.coveralls", version.ref = "coveralls" }
jacoco-android = { id = "com.mxalbert.gradle.jacoco-android", version.ref = "jacocoAndroid" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncher" }
python-uv = { id = "com.pswidersk.python-uv-plugin", version.ref = "pythonUv" }
app-versioning = { id = "io.github.reactivecircus.app-versioning", version.ref = "appVersioning"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
