name: Copy .po files to po-files branch
on:
  push:
    branches:
      - main

jobs:
  copy:
    name: Copy to po-files
    if: github.repository_owner == 'connectbot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Push subdirectory
        uses: s0/git-publish-subdir-action@ac113f6bfe8896e85a373534242c949a7ea74c98 # develop
        env:
          REPO: self
          BRANCH: po-files
          FOLDER: app/locale
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Automated export to {target-branch}\n\nFrom branch main commit {long-sha}:\n\n{msg}"
          SKIP_EMPTY_COMMITS: true
