# This workflow imports translations from Launchpad

name: Translations import
on:
  schedule:
  # Runs at 10PM PST
  - cron: '0 6 * * *'
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/translations-import.yml"
      - "translations/**"

jobs:
  import:
    name: Import translations from Launchpad
    runs-on: ubuntu-latest
    if: github.repository_owner == 'connectbot'

    env:
      BAZAAR_URI: lp:~kennyr/connectbot/po-output
      PO_SUBDIR: app/locale

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install bazaar
      run: |
        sudo apt-get update && \
        sudo apt-get install -y --no-install-recommends \
            bzr \
            ca-certificates \
            rsync

    - name: Branch Bazaar translation exports
      run: |
        cd ${{ runner.temp }}
        bzr branch lp:~kennyr/connectbot/po-output
        cd po-output
        echo "REVNO=$(bzr revno)" >> $GITHUB_ENV

    - name: Copy exported translations to workspace
      run: |
        rsync -av --exclude .bzr \
            --exclude '**/oc.po' --exclude '**/ca@valencia.po' --exclude '**/tk.po' \
            "${{ runner.temp }}/${BAZAAR_URI##*/}/" "${GITHUB_WORKSPACE}/${PO_SUBDIR}/"
        echo $REVNO > "${GITHUB_WORKSPACE}/${PO_SUBDIR}/.revno"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

    - name: Try importing the translations
      run: |
        TRANSLATIONS_ONLY=1 ./gradlew :translations:importToAndroid

    - name: Create pull request
      if: github.event_name != 'pull_request'
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          Automated translations import

          Translations imported from Launchpad.
        author: Translations Bot <no-reply+translations@connectbot.org>
        title: '[Translations] Automatic update'
        body: |
          Automated import of translations from Launchpad.
        labels: translations, automated pr
        assignees: kruton
        reviewers: kruton
        branch: translations/import

    - name: Report pull request creation
      if: github.event_name != 'pull_request'
      run: echo "Created pull request number ${{ env.PULL_REQUEST_NUMBER }}"
